"""creacion_inicial_postgres

Revision ID: ad01299e5362
Revises: 
Create Date: 2026-06-30 18:30:45.043381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad01299e5362'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accion',
    sa.Column('id_accion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_accion')
    )
    op.create_table('categoria_ganado',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('estados',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('tipo_doc',
    sa.Column('id_tipo_doc', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_doc')
    )
    op.create_table('precio',
    sa.Column('id_precio', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('precio_mercado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_ganado.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_precio')
    )
    op.create_table('raza',
    sa.Column('id_raza', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_ganado.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_raza')
    )
    op.create_table('requisitos_docs_rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_tipo_doc', sa.Integer(), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_tipo_doc'], ['tipo_doc.id_tipo_doc'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_tipo_doc')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_accion', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_accion'], ['accion.id_accion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_table('datos_veterinarios',
    sa.Column('id_docs_vet', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('cedula_profesional', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('universidad', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_docs_vet'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('documentos',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_usuario_subio', sa.Integer(), nullable=False),
    sa.Column('id_validador', sa.Integer(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_tipo_doc', sa.Integer(), nullable=False),
    sa.Column('uri_archivo', sa.String(length=500), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_tipo_doc'], ['tipo_doc.id_tipo_doc'], ),
    sa.ForeignKeyConstraint(['id_usuario_subio'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_validador'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('productores',
    sa.Column('id_productor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('capacidad_animales', sa.Integer(), nullable=True),
    sa.Column('superficie_hectareas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_productor'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('animal',
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('arete_id', sa.String(length=50), nullable=False),
    sa.Column('id_productor', sa.Integer(), nullable=False),
    sa.Column('id_raza', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('tiene_crias', sa.Boolean(), nullable=False),
    sa.Column('proposito_produccion', sa.String(length=100), nullable=False),
    sa.Column('condicion_general', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_certificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('token_qr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_productor'], ['productores.id_productor'], ),
    sa.ForeignKeyConstraint(['id_raza'], ['raza.id_raza'], ),
    sa.PrimaryKeyConstraint('id_animal'),
    sa.UniqueConstraint('arete_id'),
    sa.UniqueConstraint('token_qr')
    )
    op.create_table('precio_animal',
    sa.Column('id_precio', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('precio_calidad', sa.Float(), nullable=True),
    sa.Column('precio_final', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id_animal'], ),
    sa.ForeignKeyConstraint(['id_precio'], ['precio.id_precio'], ),
    sa.PrimaryKeyConstraint('id_precio', 'id_animal')
    )
    op.create_table('solicitudes_certificacion',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('id_veterinario', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('fecha_dictamen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id_animal'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_veterinario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('certificaciones',
    sa.Column('id_certificacion', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('peso_validado', sa.Float(), nullable=False),
    sa.Column('caracteristicas_validades', sa.Text(), nullable=False),
    sa.Column('observaciones_medicas', sa.Text(), nullable=True),
    sa.Column('dictamen', sa.String(length=100), nullable=False),
    sa.Column('fecha_certificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_certificacion.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_certificacion'),
    sa.UniqueConstraint('id_solicitud')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificaciones')
    op.drop_table('solicitudes_certificacion')
    op.drop_table('precio_animal')
    op.drop_table('animal')
    op.drop_table('productores')
    op.drop_table('documentos')
    op.drop_table('datos_veterinarios')
    op.drop_table('bitacora')
    op.drop_table('usuarios')
    op.drop_table('requisitos_docs_rol')
    op.drop_table('raza')
    op.drop_table('precio')
    op.drop_table('tipo_doc')
    op.drop_table('roles')
    op.drop_table('estados')
    op.drop_table('categoria_ganado')
    op.drop_table('accion')
    # ### end Alembic commands ###
