"""ajuste_der

Revision ID: cf0c580de35b
Revises: ad01299e5362
Create Date: 2026-07-16 20:01:35.750371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf0c580de35b'
down_revision: Union[str, Sequence[str], None] = 'ad01299e5362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if {
        "enfermedad",
        "documentos_animal",
        "enfermedad_animal",
    }.issubset(existing_tables):
        return

    op.create_table('enfermedad',
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje_penalizacion', sa.Float(), nullable=False),
    sa.Column('requiere_cuarentena', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_enfermedad')
    )
    op.create_table('documentos_animal',
    sa.Column('id_doc_animal', sa.Integer(), nullable=False),
    sa.Column('id_usuario_subio', sa.Integer(), nullable=False),
    sa.Column('id_validador', sa.Integer(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_tipo_doc', sa.Integer(), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_tipo_doc'], ['tipo_doc.id_tipo_doc'], ),
    sa.ForeignKeyConstraint(['id_usuario_subio'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_validador'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_doc_animal')
    )
    op.create_table('enfermedad_animal',
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('fecha_deteccion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id_animal'], ),
    sa.ForeignKeyConstraint(['id_enfermedad'], ['enfermedad.id_enfermedad'], ),
    sa.PrimaryKeyConstraint('id_enfermedad', 'id_animal')
    )
    op.drop_table('documentos')
    op.add_column('animal', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('animal', sa.Column('color_pelaje', sa.String(length=100), nullable=True))
    op.add_column('animal', sa.Column('estado_salud', sa.String(length=100), nullable=True))
    op.add_column('animal', sa.Column('foto_frontal', sa.String(length=500), nullable=True))
    op.add_column('animal', sa.Column('foto_lateral', sa.String(length=500), nullable=True))
    op.add_column('precio', sa.Column('precio_base_kilo', sa.Float(), nullable=False))
    op.add_column('precio', sa.Column('fecha_vigencia', sa.DateTime(), nullable=False))
    op.add_column('precio', sa.Column('activo', sa.Boolean(), nullable=False))
    op.drop_column('precio', 'precio_mercado')
    op.add_column('precio_animal', sa.Column('valor_agregado', sa.Float(), nullable=True))
    op.add_column('precio_animal', sa.Column('modificador_porcentual', sa.Float(), nullable=True))
    op.add_column('precio_animal', sa.Column('precio_base_aplicado', sa.Float(), nullable=True))
    op.add_column('precio_animal', sa.Column('peso_al_calculo', sa.Float(), nullable=True))
    op.add_column('precio_animal', sa.Column('fecha_calculo', sa.DateTime(), nullable=True))
    op.drop_column('precio_animal', 'precio_calidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if not {"enfermedad", "documentos_animal", "enfermedad_animal"}.issubset(existing_tables):
        return

    op.add_column('precio_animal', sa.Column('precio_calidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('precio_animal', 'fecha_calculo')
    op.drop_column('precio_animal', 'peso_al_calculo')
    op.drop_column('precio_animal', 'precio_base_aplicado')
    op.drop_column('precio_animal', 'modificador_porcentual')
    op.drop_column('precio_animal', 'valor_agregado')
    op.add_column('precio', sa.Column('precio_mercado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('precio', 'activo')
    op.drop_column('precio', 'fecha_vigencia')
    op.drop_column('precio', 'precio_base_kilo')
    op.drop_column('animal', 'foto_lateral')
    op.drop_column('animal', 'foto_frontal')
    op.drop_column('animal', 'estado_salud')
    op.drop_column('animal', 'color_pelaje')
    op.drop_column('animal', 'notas')
    op.create_table('documentos',
    sa.Column('id_documento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario_subio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_validador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_estado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_doc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uri_archivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_revision', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], name=op.f('documentos_id_estado_fkey')),
    sa.ForeignKeyConstraint(['id_tipo_doc'], ['tipo_doc.id_tipo_doc'], name=op.f('documentos_id_tipo_doc_fkey')),
    sa.ForeignKeyConstraint(['id_usuario_subio'], ['usuarios.id_usuario'], name=op.f('documentos_id_usuario_subio_fkey')),
    sa.ForeignKeyConstraint(['id_validador'], ['usuarios.id_usuario'], name=op.f('documentos_id_validador_fkey')),
    sa.PrimaryKeyConstraint('id_documento', name=op.f('documentos_pkey'))
    )
    op.drop_table('enfermedad_animal')
    op.drop_table('documentos_animal')
    op.drop_table('enfermedad')
    # ### end Alembic commands ###
