"""Schemas expuestos por el modulo admin."""

from app.schemas import (
	BitacoraCreate,
	BitacoraResponse,
	CategoriaGanadoCreate,
	CategoriaGanadoResponse,
	DocumentoCreate,
	DocumentoResponse,
	EnfermedadAnimalCreate,
	EnfermedadAnimalResponse,
	EnfermedadCreate,
	EnfermedadResponse,
	PrecioAnimalCreate,
	PrecioAnimalResponse,
	PrecioCreate,
	PrecioResponse,
	RazaCreate,
	RazaResponse,
	RequisitoDocRolCreate,
	RequisitoDocRolResponse,
	RequisitoDocRolUpdate,
	TipoDocCreate,
	TipoDocResponse,
)

__all__ = [
	"BitacoraCreate",
	"BitacoraResponse",
	"CategoriaGanadoCreate",
	"CategoriaGanadoResponse",
	"DocumentoCreate",
	"DocumentoResponse",
	"EnfermedadAnimalCreate",
	"EnfermedadAnimalResponse",
	"EnfermedadCreate",
	"EnfermedadResponse",
	"PrecioAnimalCreate",
	"PrecioAnimalResponse",
	"PrecioCreate",
	"PrecioResponse",
	"RazaCreate",
	"RazaResponse",
	"RequisitoDocRolCreate",
	"RequisitoDocRolResponse",
	"RequisitoDocRolUpdate",
	"TipoDocCreate",
	"TipoDocResponse",
]
